/*POR_AJUDANTE*/
SELECT * FROM POR_AJUDANTE;
ALTER TABLE POR_AJUDANTE
ADD CRIACAO DATETIME DEFAULT GETDATE();

/*POR_CAMINHOES*/
SELECT * FROM POR_CAMINHOES;

SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'POR_CAMINHOES'

ALTER TABLE POR_CAMINHOES
ADD CRIACAO DATETIME DEFAULT GETDATE();

UPDATE POR_CAMINHOES SET CRIACAO = HORARIO_CHEGADA;

ALTER TABLE POR_CAMINHOES
ALTER COLUMN HORARIO_CHEGADA TIME;

ALTER TABLE POR_CAMINHOES
ALTER COLUMN HORARIO_ENTRADA TIME;

ALTER TABLE POR_CAMINHOES
ALTER COLUMN HORARIO_SAIDA TIME;

/*POR_CARRETA*/
SELECT * FROM POR_CARRETA;
ALTER TABLE POR_CARRETA
ADD CRIACAO DATETIME DEFAULT GETDATE();

/*POR_ENTRADA_SAIDA*/
SELECT * FROM POR_ENTRADA_SAIDA;

ALTER TABLE POR_ENTRADA_SAIDA
ALTER COLUMN CHEGADA TIME;

ALTER TABLE POR_ENTRADA_SAIDA
ALTER COLUMN ENTRADA TIME;

ALTER TABLE POR_ENTRADA_SAIDA
ALTER COLUMN SAIDA TIME;

/*POR_ESTACIONAMENTO*/
SELECT * FROM POR_ESTACIONAMENTO;

ALTER TABLE POR_ESTACIONAMENTO
ADD CRIACAO DATETIME DEFAULT GETDATE();

UPDATE POR_ESTACIONAMENTO SET CRIACAO = ENTRADA;
UPDATE POR_ESTACIONAMENTO SET CRIACAO = SAIDA WHERE ENTRADA IS NULL;

ALTER TABLE POR_ESTACIONAMENTO
ALTER COLUMN ENTRADA TIME;

ALTER TABLE POR_ESTACIONAMENTO
ALTER COLUMN SAIDA TIME;

/*POR_FINALIZADO*/
SELECT * FROM POR_FINALIZADO;
DROP TABLE POR_FINALIZADO;

/*POR_VISITANTE*/
SELECT * FROM POR_VISITANTE;

ALTER TABLE POR_VISITANTE
ADD IMAGEM VARBINARY(MAX)

-- ADICIONA FOTOS OS REGISTRO UPDATE POR_VISITANTE SET IMAGEM 

ALTER TABLE POR_VISITANTE
DROP COLUMN FOTO;