USE [master]
GO

/****** Object:  Database [PROGRAMAS]    Script Date: 28/06/2024 17:50:22 ******/
CREATE DATABASE [PROGRAMAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PROGRAMAS_HOM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.OSEIAS_TI\MSSQL\DATA\PROGRAMAS_HOM.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PROGRAMAS_HOM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.OSEIAS_TI\MSSQL\DATA\PROGRAMAS_HOM_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PROGRAMAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PROGRAMAS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PROGRAMAS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PROGRAMAS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PROGRAMAS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PROGRAMAS] SET ARITHABORT OFF 
GO

ALTER DATABASE [PROGRAMAS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PROGRAMAS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PROGRAMAS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PROGRAMAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PROGRAMAS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PROGRAMAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PROGRAMAS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PROGRAMAS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PROGRAMAS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PROGRAMAS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PROGRAMAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PROGRAMAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PROGRAMAS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PROGRAMAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PROGRAMAS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PROGRAMAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PROGRAMAS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PROGRAMAS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PROGRAMAS] SET  MULTI_USER 
GO

ALTER DATABASE [PROGRAMAS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PROGRAMAS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PROGRAMAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PROGRAMAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PROGRAMAS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PROGRAMAS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PROGRAMAS] SET QUERY_STORE = ON
GO

ALTER DATABASE [PROGRAMAS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PROGRAMAS] SET  READ_WRITE 
GO


