USE [PROGRAMAS]
GO

DROP PROCEDURE IF EXISTS dbo.truncateEcommerce
GO

CREATE PROCEDURE dbo.truncateEcommerce
AS
    BEGIN
        DECLARE @TABLES_TO_DELETE VARCHAR(max);

        SELECT @TABLES_TO_DELETE = STRING_AGG('DELETE FROM [' + TABLE_NAME + ']; DBCC CHECKIDENT (' + TABLE_NAME + ', RESEED, 0);', ' ') FROM INFORMATION_SCHEMA.TABLES;

        EXEC (@TABLES_TO_DELETE);
    END
GO
