SELECT US.ID_USUARIO, LG.LOGIN, US.EMAIL, US.NOME, US.CENTRO_CUSTO FROM ACS_USUARIO US
INNER JOIN ACS_LOGIN LG ON LG.ID_LOGIN = US.ID_LOGIN
WHERE US.NOME LIKE '%GIO%';

SELECT US.ID_USUARIO, LG.LOGIN, US.EMAIL, US.NOME, US.CENTRO_CUSTO FROM ACS_USUARIO US
INNER JOIN ACS_LOGIN LG ON LG.ID_LOGIN = US.ID_LOGIN
WHERE US.CENTRO_CUSTO = 20100;

SELECT US.ID_USUARIO, LG.LOGIN, US.EMAIL, US.NOME, US.CENTRO_CUSTO FROM ACS_USUARIO US
INNER JOIN ACS_LOGIN LG ON LG.ID_LOGIN = US.ID_LOGIN
WHERE US.EMAIL LIKE '%marketing1@induscabos.com.br%';