-- Busca Id Pergnta
-- 5734, 5735, 5736, 5737, 5738, 5739, 5740, 5741

-- Busca resposta repetidas
--DECLARE @ID_PERGUNTA INT = 5737;
--SELECT * FROM FOR_RESPOSTA WHERE ID_PERGUNTA = @ID_PERGUNTA AND ID_USUARIO IN 
--(SELECT ID_USUARIO FROM FOR_RESPOSTA WHERE ID_PERGUNTA = @ID_PERGUNTA GROUP BY ID_USUARIO HAVING COUNT(1) > 1)

-- Deleta duplicados
DECLARE @ID_PERGUNTA INT = 5734;
WITH DUPLICADOS AS (SELECT ROW_NUMBER() OVER (PARTITION BY ID_USUARIO, ID_PERGUNTA
ORDER BY (ID_USUARIO)) AS DUPLICADO, * FROM FOR_RESPOSTA WHERE ID_PERGUNTA = @ID_PERGUNTA)
----------------------------------------------------------------------------------
DELETE FROM FOR_RESPOSTA WHERE ID_RESPOSTA IN (SELECT ID_RESPOSTA FROM DUPLICADOS WHERE DUPLICADO > 1)
--DELETE FROM FOR_RES_OPC WHERE ID_RESPOSTA IN (SELECT ID_RESPOSTA FROM DUPLICADOS WHERE DUPLICADO > 1)