/** Script da P5DADOS **/
DECLARE @NUM VARCHAR(10) = 'NUMERO DO CONTROLE';
UPDATE ZD7010 SET ZD7_PLACA = '(---)', ZD7_NOME = '(---)', ZD7_HRMOTO = '' WHERE ZD7_NUM = @NUM;
SELECT * FROM ZD7010 WHERE ZD7_NUM = @NUM;

/** Script do programas **/
DECLARE @NUM VARCHAR(10) = 'NUMERO DO CONTROLE';
UPDATE POR_CAMINHOES SET NOTA_FISCAL = '', CODIGO_CLIENTE = '', ZD7_NUM = '' WHERE ZD7_NUM = @NUM;
SELECT * FROM POR_CAMINHOES WHERE ZD7_NUM = @NUM;