-- Libera senha;
DECLARE @RE_FUNCIONARIO INT = 000000;
DECLARE @SENHA VARBINARY(256) = (SELECT SENHA FROM ACS_LOGIN WHERE RE_FUNCIONARIO = @RE_FUNCIONARIO);
UPDATE ACS_HISTORICOSENHA SET SENHA = @SENHA WHERE ID_HISTORICO_SENHA = 1;
UPDATE ACS_LOGIN SET SENHA = HASHBYTES('SHA2_256', '12') WHERE RE_FUNCIONARIO = @RE_FUNCIONARIO;